### ISSUE TITLE
role not found

### ISSUE THREAD

**Issue by dfang** [MonolithProjects/action-molecule#2]
```
molecule init role xxx.yyy
```
then add these lines to .github/workflow/molecule.yml
```
on: push

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: "centos8"
            tag: "latest"
          - os: "nmusatti/ubuntu2204-pys"
            tag: "latest"
          - os: "nmusatti/centos-stream8-pys"
            tag: "latest"
    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Molecule
        uses: MonolithProjects/action-molecule@v1.4.1
        with:
          os: ${{ matrix.config.os }}
          tag: ${{ matrix.config.tag }}
          molecule_command: converge
```

molecule version
```
λ molecule --version
molecule 5.0.1 using python 3.11 
    ansible:2.14.5
    delegated:5.0.1 from molecule
    docker:2.1.0 from molecule_docker requiring collections: community.docker>=3.0.2 ansible.posix>=1.4.0
```

full error messages on online workflow:  
https://github.com/dfang/ansible_role_asdf/actions/runs/5460479641/jobs/9937508519
